import tkinter as r
import tkinter.font as tkfont
inst=r.Tk()
inst.title("INSTRUCTIONS")
inst.configure(bg='deep sky blue')
buttonsty=tkfont.Font(family="Lucida Grande",size=2)
buttonsty.configure(size=20)
f1=tkfont.Font(family="Lucida Grande",size=2)
f1.configure(size=10)
l=r.Label(inst,text="Instructions",font=buttonsty)
l.pack()
l.configure(bg='deep sky blue')
l1=r.Label(inst,text="1.You have the access to move the basket.",font=f1)
l1.pack()
l1.configure(bg='deep sky blue')
l2=r.Label(inst,text="2.Use the left arrow to  move the basket left and right to move right.",font=f1)
l2.pack()
l2.configure(bg='deep sky blue')
l3=r.Label(inst,text="3.You have 3 lives.",font=f1)
l3.pack()
l3.configure(bg='deep sky blue')
l4=r.Label(inst,text="4.For each drop of life will be deducted.",font=f1)
l4.pack()
l4.configure(bg='deep sky blue')
l5=r.Label(inst,text="5.Each egg catch adds 10 points.",font=f1)
l5.pack()
l5.configure(bg='deep sky blue')
l6=r.Label(inst,text="6.Play the game and have fun.",font=f1)
l6.pack()
l6.configure(bg='deep sky blue')
